name: mobile_code_challenge_solution
description: A solution to gemography's code challenge

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  provider: ^4.3.1
  pedantic: ^1.9.0
  dio: ^3.0.9
  built_value: ^7.1.0
  built_collection: ^4.3.2
  loadmore: ^1.0.4
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
